import { type NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Sidebar from "~/components/Sidebar";

const ChatSection = dynamic(() => import("~/components/ChatSection"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark relative flex h-screen overflow-hidden bg-gray-800 font-soehne">
        <Sidebar />
        <ChatSection />
      </main>
    </>
  );
};

export default Home;
